// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk1QLJRVTfwKtY_b4leB9-oOlLkfCt77U',
    appId: '1:224142785055:web:6ae1b6de0fa0e44d9f732a',
    messagingSenderId: '224142785055',
    projectId: 'appestoque-8c738',
    authDomain: 'appestoque-8c738.firebaseapp.com',
    storageBucket: 'appestoque-8c738.appspot.com',
    measurementId: 'G-ERHXDRFRYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBauptL74y4kGW6CdnpmeZhFQXMFLEC508',
    appId: '1:224142785055:android:c5b5534d70eeda359f732a',
    messagingSenderId: '224142785055',
    projectId: 'appestoque-8c738',
    storageBucket: 'appestoque-8c738.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATTgrQUH0AnXnFypZg04ib6xlJLYneaqc',
    appId: '1:224142785055:ios:333fe51e383cc88a9f732a',
    messagingSenderId: '224142785055',
    projectId: 'appestoque-8c738',
    storageBucket: 'appestoque-8c738.appspot.com',
    iosClientId: '224142785055-8g6kfv6drr4vjsj79c8rvqacml8kbiju.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATTgrQUH0AnXnFypZg04ib6xlJLYneaqc',
    appId: '1:224142785055:ios:5fa98103988b60d49f732a',
    messagingSenderId: '224142785055',
    projectId: 'appestoque-8c738',
    storageBucket: 'appestoque-8c738.appspot.com',
    iosClientId: '224142785055-4dgd7r8jmp4teibk4o6ev6r3df7oupka.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
